---
driver:
  name: vagrant
  customize:
    memory: 512
    cpuexecutioncap: 50

provisioner:
  name: chef_solo
  solo_rb:
    ssl_verify_mode: verify_peer

platforms:
  - name: ubuntu-14.04
  - name: centos-6.5

suites:
  - name: default
    run_list:
      - recipe[example]
    attributes:
